version: "3.9"

networks:
  public: {}
  private: {}

volumes:
  api-bundle: {}
  postgres-data: {}

services:
  api:
    build:
      dockerfile: Dockerfile.development
      context: "."
    volumes:
      - api-bundle:/usr/local/bundle
      - .:/rails-6-api
    environment:
      RAILS_DATABASE_URL: postgres://postgres:postgres@postgres/rails_6_api
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "3000:3000"
    networks:
      - public
      - private
    depends_on:
      - postgres
    labels:
      rails-6-api.service: api

  postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rails_6_api
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - private
    labels:
      rails-6-api.service: postgres
