#!/bin/bash
set -eo pipefail

if command -v docker > /dev/null; then
  echo "✓ Docker is installed"
else
  echo "✗ Docker is not installed"
  exit 1
fi

if command -v docker-compose > /dev/null; then
  echo "✓ Docker-compose is installed"
else
  echo "✗ Docker-compose is not installed"
  exit 1
fi

if docker version > /dev/null; then
  echo "✓ Docker daemon is up"
else
  echo "✗ Docker daemon is down"
  exit 1
fi
